package ie.roryRoams.fourSquareCipher;

import static java.lang.System.out;

import java.util.Random;
import java.util.Scanner;

public class CipherMenu {
	private Scanner s = new Scanner(System.in);
	String decryptedText;
	StringBuilder all;
	private FourSquareCipher cipher;
	private boolean keepRunning = true;
	LoadNSave rw = new LoadNSave();

	public void start() {
		while (keepRunning) {
			try {
				showOptions();
				int choice = Integer.parseInt(s.next());
				s.nextLine();
				switch (choice) {
				case 1 -> begin();
				case 2 -> findOutMore();
				case 3 -> keepRunning = false;
				default -> out.println("[Error] Invalid Selection");

				}
			} catch (Exception e) {
				out.println("please enter a valid number.");
				continue;
			}

		}

		out.println("[Info] Exiting Rory's Four Square Cipher");
	}

	private void showOptions() {
		out.println("********************************");
		out.println("**	 Rory's Four Square Cipher		 **");
		out.println("********************************");
		out.println("(1) Start");
		out.println("(2) Learn how to use the Four Square Cipher ");
		out.println("(3) Quit");
		out.println("Select an option [1-3]>");
	}

	private Object findOutMore() {
		// TODO Auto-generated method stub
		return null;
	}

	private void begin() {
		while (keepRunning) {
			keyChoice();
			int choice = Integer.parseInt(s.next());
			s.nextLine();
			switch (choice) {
			case 1 -> setKeys();
			case 2 -> generatekeys();
			case 3 -> {
				reset();
				return; // This exits the Key menu and lands you back in start
			}
			default -> out.println("[Error] Invalid Selection");

			}
			if (cipher == null)
				return;
		}
	}

	private void keyChoice() {
		out.println("********************************");
		out.println("**	 Rory's Four Square Cipher		 **");
		out.println("**	 would you like to add your own keys " + "or have them generated by the program. **");
		out.println("********************************");
		out.println("(1) Enter your own keys");
		out.println("(2) Generate keys");
		out.println("(3) Start Again");
		out.println("Select an option [1-3]>");

	}

	private void setKeys() {
		out.println("********************************");
		out.println("**	 Rory's Four Square Cipher		 **");
		out.println("********************************");
		System.out.println("Enter key 1: ");
		String key1 = s.nextLine();
		System.out.println("Enter key 2: ");
		String key2 = s.nextLine();
		cipher = new FourSquareCipher(key1, key2);
		pickEncrypt();
		if (cipher == null)
			return;
		out.println("(3) Start Again");
		out.println("Select an option [1-3]>");

	}

	private void generatekeys() {

		String key1 = generatekey();
		String key2 = generatekey();

		cipher = new FourSquareCipher(key1, key2);
		pickEncrypt();

		if (cipher == null)
			return;
	}

	// using the shuffle yates from https://www.youtube.com/watch?v=-JZVfi4u8PA
	// and
	// https://www.geeksforgeeks.org/dsa/shuffle-a-given-array-using-fisher-yates-shuffle-algorithm/
	private String generatekey() {
		char[] arr = { 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
				'U', 'V', 'W', 'X', 'Y', 'Z' };
		Random random = new Random();

		for (int i = arr.length - 1; i > 0; i--) {
			int j = random.nextInt(i + 1);
			char temp = arr[i];
			arr[i] = arr[j];
			arr[j] = temp;
		}

		return new String(arr);

	}

	private void pickEncrypt() {
		while (keepRunning) {
			URLorFILE();
			int choice = Integer.parseInt(s.next());
			s.nextLine();
			switch (choice) {
			case 1 -> urlEncrypt();
			case 2 -> textEncrypt();
			case 3 -> {
				reset(); // resets all the variables in the menu
				return; // this goes back to menu
			}
			default -> out.println("[Error] Invalid Selection");

			}
			if (cipher == null)
				return;
		}
	}

	private void URLorFILE() {
		out.println("********************************");
		out.println("**	 Rory's Four Square Cipher		 **");
		out.println("********************************");
		out.println("Press 1 to chose a url to encrypt ");
		out.println("Press 2 to chose a text file to encrypt ");
		out.println("(3) Start Again");
		out.println("Select an option [1-3]>");

	}

	private void urlEncrypt() {
		try {
			all = null;
			String pt;
			URLParser search = new URLParser();
			System.out.println("Please enter a URL, make sure it is the full URL and "
					+ "include HTTPS at the start or it wont work ");
			pt = s.nextLine();
			String midtext = search.fetchURL(pt);
			String encrypted = cipher.encrypt(midtext);
			all.append(encrypted);
			decryptedText = cipher.decrypt(encrypted);
			all.append(decryptedText);
			save();
		} catch (Exception e) {
			System.out.println("Could not load URL");
			return; // go back to menu
		}

	}

	private void textEncrypt() {
		all = null;
		String pt;
		String loadedText;
		String encryptedText;
		System.out.println("Please enter a text file from the files in your project, ");
		System.out.println("make sure it is the full text file name with the .txt ");
		System.out.println("or what ever extention is on it ");
		pt = s.nextLine();

		if (pt.trim().isEmpty()) {
			out.println("[Error] No filename entered.");
			return;
		}

		try {

			loadedText = rw.load(pt);
			encryptedText = cipher.encrypt(loadedText);
			all.append(encryptedText);
			decryptedText = cipher.decrypt(encryptedText);
			all.append(decryptedText);
			save();

		} catch (Exception e) {
			out.println("");
			out.println("[Error]: Could not find or read '" + pt + "'.");
			out.println("Make sure the file is in the project folder and the name is correct.");
			out.println("");
		}

	}

	private void save() {
		String pt;

		System.out.println("Please enter what you would like to save your file as, ");
		System.out.println("and it will appear in your project folder ");
		System.out.println("please use an extenstion. eg. testing.txt");
		pt = s.nextLine();

		if (pt.trim().isEmpty() || decryptedText == null) {
			System.out.println("[Error] There was an error saving. please try again!");
			return;
		}
		try {
			rw.save(all, pt);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void reset() {
		this.decryptedText = "";
		this.cipher = null;
		this.all = null;
		out.println();
		out.println("Returning to Main Menu");
		out.println();

	}

}
